#!/bin/bash

# Helper script to update lifecycle tests with new MCP client
# This script documents the manual changes needed for each test

echo "📝 Lifecycle Test Update Checklist"
echo ""
echo "For each of the following files:"
echo "  - test/test-cifs-lifecycle.js"
echo "  - test/test-export-policy-lifecycle.js"
echo "  - test/test-qos-lifecycle.js"
echo ""
echo "Make these changes:"
echo ""
echo "1. Add import at top:"
echo "   import { McpTestClient } from './mcp-test-client.js';"
echo ""
echo "2. Remove embedded callMcpTool() function (replace with McpTestClient)"
echo ""
echo "3. Update constructor to accept serverAlreadyRunning:"
echo "   constructor(mode = 'stdio', serverAlreadyRunning = false)"
echo "   Add: this.serverAlreadyRunning = serverAlreadyRunning;"
echo "   Add: this.mcpClient = null;"
echo ""
echo "4. Update startHttpServer() to check serverAlreadyRunning"
echo "5. Update stopHttpServer() to check serverAlreadyRunning"
echo ""
echo "6. Replace callMcpTool() calls with this.mcpClient pattern"
echo ""
echo "7. Add extractText() helper method"
echo ""
echo "8. Update main() to accept --server-running flag"
echo ""
echo "9. Update all result.content[0].text with this.extractText(result)"
echo ""

echo "✅ test-volume-lifecycle.js is DONE as template reference"
