#!/bin/bash

# Tool count verification script for NetApp ONTAP MCP Server

echo "=== NetApp ONTAP MCP Server Tool Count Verification ==="
echo ""

echo "📊 Expected Tools Count: 46"
echo ""
echo "🔍 Tool Categories:"
echo "   • Legacy single-cluster tools: 8"
echo "   • Multi-cluster management tools: 10" 
echo "   • Snapshot policy management: 7"
echo "   • Export policy management: 9"
echo "   • CIFS/SMB share management: 8"
echo "   • Volume configuration/update: 4"
echo ""

echo "📋 Complete Tool List:"
echo ""

echo "Legacy Single-Cluster Tools (8):"
echo "  1. get_cluster_info"
echo "  2. list_volumes"
echo "  3. list_svms"
echo "  4. list_aggregates"
echo "  5. get_volume_stats"
echo "  6. create_volume"
echo "  7. offline_volume"
echo "  8. delete_volume"
echo ""

echo "Multi-Cluster Management Tools (10):"
echo "  9. add_cluster"
echo " 10. list_registered_clusters"
echo " 11. get_all_clusters_info"
echo " 12. cluster_list_volumes"
echo " 13. cluster_list_svms"
echo " 14. cluster_list_aggregates"
echo " 15. cluster_create_volume"
echo " 16. cluster_offline_volume"
echo " 17. cluster_delete_volume"
echo " 18. cluster_get_volume_stats"
echo ""

echo "Snapshot Policy Management Tools (7):"
echo " 19. list_snapshot_policies"
echo " 20. get_snapshot_policy"
echo " 21. create_snapshot_policy"
echo " 22. update_snapshot_policy"
echo " 23. delete_snapshot_policy"
echo " 24. apply_snapshot_policy_to_volume"
echo " 25. remove_snapshot_policy_from_volume"
echo ""

echo "Export Policy Management Tools (9):"
echo " 26. list_export_policies"
echo " 27. get_export_policy"
echo " 28. create_export_policy"
echo " 29. delete_export_policy"
echo " 30. add_export_rule"
echo " 31. update_export_rule"
echo " 32. delete_export_rule"
echo " 33. configure_volume_nfs_access"
echo " 34. disable_volume_nfs_access"
echo ""

echo "CIFS/SMB Share Management Tools (8):"
echo " 35. list_cifs_shares"
echo " 36. get_cifs_share"
echo " 37. create_cifs_share"
echo " 38. update_cifs_share"
echo " 39. delete_cifs_share"
echo " 40. cluster_list_cifs_shares"
echo " 41. cluster_create_cifs_share"
echo " 42. cluster_delete_cifs_share"
echo ""

echo "Volume Configuration/Update Tools (4):"
echo " 43. get_volume_configuration"
echo " 44. update_volume_security_style"
echo " 45. resize_volume"
echo " 46. update_volume_comment"
echo ""

echo "✅ Fixed Issues:"
echo "   • Removed duplicate 'apply_snapshot_policy_to_volume' from volume-update-tools"
echo "   • Removed duplicate 'remove_snapshot_policy_from_volume' from volume-update-tools"
echo "   • Updated tool registrations in index.ts"
echo "   • Cleaned up duplicate imports"
echo "   • Added 8 new CIFS/SMB share management tools"
echo ""

echo "🎯 Result: VS Code should now show all 46 tools in the MCP tools dropdown"
echo ""

echo "📝 To verify:"
echo "   1. Restart VS Code"
echo "   2. Go to MCP tools dropdown for 'netapp-ontap-mcp'"
echo "   3. Check that 46 tools are listed (including CIFS tools)"
echo "   4. Verify tools from all categories are present"